# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
            args: ["--allow-multiple-documents"]
          - id: check-ast
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: mixed-line-ending
    - repo: local
      hooks:
          - id: prettier
            name: prettier
            description: Runs Prettier Code Formatter
            entry: prettier --write --ignore-unknown
            args: ["--tab-width=4"]
            language: node
            types:
                - text
            additional_dependencies:
                - prettier@3.8.1
            exclude: |
                (?x)(
                  .specify/|
                  .claude/
                )
